name: CI/CD Coin Clicker Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  #CI
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Copy repository code
      uses: actions/checkout@v4

    - name: Quick syntax check
      run: node -js --check scripts/*.js

  #CD
  deploy-to-pages:
    needs: check-code
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Copy repository code
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
