name: CI/CD Coin Clicker Pipeline

on:
  push:
    branches: [ main ]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Copy repository code
      uses: actions/checkout@v4

    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install eslint @eslint/js globals @playwright/test http-server --save-dev

    - name: Run ESLint Check
      run: npx eslint scripts/

    - name: Install Playwright OS Dependencies
      run: npx playwright install-deps chromium

    - name: Install Playwright Browsers
      run: npx playwright install chromium

    - name: Run UI Tests
      env:
        CI: true
      run: npm test

  deploy-to-pages:
    needs: check-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Copy repository code
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
